name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  CINIRA_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.CINIRA_ARTIFACTS_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "21"
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm install
      - run: npm audit signatures
      - run: npx semantic-release
        env:
          CINIRA_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.CINIRA_ARTIFACTS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
