name: Test pull request
on: [pull_request]

permissions:
  contents: read

env:
  CCF_TEST_DATA_PASSPHRASE: ${{ secrets.CCF_TEST_DATA_PASSPHRASE }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          cache: gradle
      - name: Test
        run: ./gradlew --no-daemon javadoc test
      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ./build/test-results/test/*.xml
